// This file is @generated by prost-build.
/// CompactBlock is a minimal block representation for efficient sync
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactBlock {
    /// Protocol version
    #[prost(uint32, tag = "1")]
    pub proto_version: u32,
    /// Block height
    #[prost(uint64, tag = "2")]
    pub height: u64,
    /// Block hash (32 bytes)
    #[prost(bytes = "vec", tag = "3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// Previous block hash (32 bytes)
    #[prost(bytes = "vec", tag = "4")]
    pub prev_hash: ::prost::alloc::vec::Vec<u8>,
    /// Block timestamp
    #[prost(uint32, tag = "5")]
    pub time: u32,
    /// Full block header (80 bytes)
    #[prost(bytes = "vec", tag = "6")]
    pub header: ::prost::alloc::vec::Vec<u8>,
    /// Compact transactions
    #[prost(message, repeated, tag = "7")]
    pub vtx: ::prost::alloc::vec::Vec<CompactTx>,
}
/// CompactTx is a minimal transaction representation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactTx {
    /// Index within the block
    #[prost(uint64, tag = "1")]
    pub index: u64,
    /// Transaction hash (32 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// Transaction fee in satoshis
    #[prost(uint64, tag = "3")]
    pub fee: u64,
    #[prost(message, repeated, tag = "4")]
    pub inputs: ::prost::alloc::vec::Vec<CompactInput>,
    #[prost(message, repeated, tag = "5")]
    pub outputs: ::prost::alloc::vec::Vec<CompactOutput>,
}
/// CompactInput represents a transaction input
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactInput {
    /// Previous transaction hash
    #[prost(bytes = "vec", tag = "1")]
    pub prev_tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// Previous output index
    #[prost(uint32, tag = "2")]
    pub prev_index: u32,
    /// Value spent (if known)
    #[prost(uint64, tag = "3")]
    pub value: u64,
    /// Source address (if known)
    #[prost(string, tag = "4")]
    pub address: ::prost::alloc::string::String,
}
/// CompactOutput represents a transaction output
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactOutput {
    /// Output value in satoshis
    #[prost(uint64, tag = "1")]
    pub value: u64,
    /// Output script
    #[prost(bytes = "vec", tag = "2")]
    pub script_pub_key: ::prost::alloc::vec::Vec<u8>,
    /// Destination address (if parseable)
    #[prost(string, tag = "3")]
    pub address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockId {
    #[prost(uint64, tag = "1")]
    pub height: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockRange {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<BlockId>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<BlockId>,
}
/// Reserved for future chain specification
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainSpec {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Empty {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightdInfo {
    /// Server version
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Server vendor name
    #[prost(string, tag = "2")]
    pub vendor: ::prost::alloc::string::String,
    /// Transparent address support
    #[prost(bool, tag = "3")]
    pub taddr_support: bool,
    /// Network name (main, test, regtest)
    #[prost(string, tag = "4")]
    pub chain_name: ::prost::alloc::string::String,
    /// Current best block height
    #[prost(uint64, tag = "5")]
    pub block_height: u64,
    /// Current best block hash
    #[prost(string, tag = "6")]
    pub best_block_hash: ::prost::alloc::string::String,
    /// Estimated network height
    #[prost(uint64, tag = "7")]
    pub estimated_height: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawTransaction {
    /// Raw transaction bytes
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Block height (0 if mempool)
    #[prost(uint64, tag = "2")]
    pub height: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendResponse {
    /// 0 = success, non-zero = error
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    /// Error description
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    /// Transaction hash if successful
    #[prost(bytes = "vec", tag = "3")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxFilter {
    /// Block containing the transaction
    #[prost(message, optional, tag = "1")]
    pub block: ::core::option::Option<BlockId>,
    /// Transaction index in block
    #[prost(uint64, tag = "2")]
    pub index: u64,
    /// Transaction hash
    #[prost(bytes = "vec", tag = "3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAddressUtxosArg {
    /// List of addresses to query
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Minimum block height
    #[prost(uint64, tag = "2")]
    pub start_height: u64,
    /// Maximum number of UTXOs to return
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddressUtxo {
    /// Address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Transaction hash (32 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    /// Output index
    #[prost(uint32, tag = "3")]
    pub index: u32,
    /// Output script
    #[prost(bytes = "vec", tag = "4")]
    pub script: ::prost::alloc::vec::Vec<u8>,
    /// Value in satoshis
    #[prost(int64, tag = "5")]
    pub value_sat: i64,
    /// Block height (0 if unconfirmed)
    #[prost(uint64, tag = "6")]
    pub height: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAddressUtxosReply {
    #[prost(message, repeated, tag = "1")]
    pub address_utxos: ::prost::alloc::vec::Vec<AddressUtxo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceArg {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBalanceReply {
    /// Confirmed balance in satoshis
    #[prost(int64, tag = "1")]
    pub confirmed_balance: i64,
    /// Unconfirmed balance in satoshis
    #[prost(int64, tag = "2")]
    pub pending_balance: i64,
    /// Total balance in satoshis
    #[prost(int64, tag = "3")]
    pub total_balance: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAddressStatsArg {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAddressStatsReply {
    /// Number of funded outputs
    #[prost(uint64, tag = "1")]
    pub funded_txo_count: u64,
    /// Sum of funded outputs
    #[prost(uint64, tag = "2")]
    pub funded_txo_sum: u64,
    /// Number of spent outputs
    #[prost(uint64, tag = "3")]
    pub spent_txo_count: u64,
    /// Sum of spent outputs
    #[prost(uint64, tag = "4")]
    pub spent_txo_sum: u64,
    /// Total transaction count
    #[prost(uint64, tag = "5")]
    pub tx_count: u64,
    /// Current balance
    #[prost(int64, tag = "6")]
    pub balance: i64,
    /// First transaction timestamp
    #[prost(uint64, tag = "7")]
    pub first_seen_tx_time: u64,
    /// Last transaction timestamp
    #[prost(uint64, tag = "8")]
    pub last_seen_tx_time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WalletInfo {
    /// Wallet address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Current balance in satoshis
    #[prost(int64, tag = "2")]
    pub balance: i64,
    /// Total transaction count
    #[prost(uint64, tag = "3")]
    pub tx_count: u64,
    /// First seen timestamp
    #[prost(uint64, tag = "4")]
    pub first_seen_time: u64,
    /// Last seen timestamp
    #[prost(uint64, tag = "5")]
    pub last_seen_time: u64,
    /// Rank by balance (1 = highest)
    #[prost(uint64, tag = "6")]
    pub rank: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTopWalletsArg {
    /// Number of wallets to return (max 1000)
    #[prost(uint32, tag = "1")]
    pub limit: u32,
    /// Offset for pagination
    #[prost(uint32, tag = "2")]
    pub offset: u32,
    /// Sort by: "balance" (default), "tx_count", "first_seen", "last_seen"
    #[prost(string, tag = "3")]
    pub sort_by: ::prost::alloc::string::String,
    /// Sort order: false = descending (default)
    #[prost(bool, tag = "4")]
    pub ascending: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTopWalletsReply {
    #[prost(message, repeated, tag = "1")]
    pub wallets: ::prost::alloc::vec::Vec<WalletInfo>,
    /// Total number of wallets with balance
    #[prost(uint64, tag = "2")]
    pub total_wallets: u64,
    /// Total supply in circulation
    #[prost(uint64, tag = "3")]
    pub total_supply: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWalletRankArg {
    /// Address to get rank for
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWalletRankReply {
    /// Wallet info with rank
    #[prost(message, optional, tag = "1")]
    pub wallet: ::core::option::Option<WalletInfo>,
    /// Total wallets for context
    #[prost(uint64, tag = "2")]
    pub total_wallets: u64,
    /// Percentile (0-100, 100 = richest)
    #[prost(double, tag = "3")]
    pub percentile: f64,
}
/// Rich list snapshot for efficient querying
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RichListEntry {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub balance: i64,
    #[prost(uint64, tag = "3")]
    pub rank: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRichListArg {
    /// Number of entries (max 10000)
    #[prost(uint32, tag = "1")]
    pub limit: u32,
    /// Pagination offset
    #[prost(uint32, tag = "2")]
    pub offset: u32,
    /// Minimum balance filter (satoshis)
    #[prost(int64, tag = "3")]
    pub min_balance: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRichListReply {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<RichListEntry>,
    #[prost(uint64, tag = "2")]
    pub total_count: u64,
    #[prost(uint64, tag = "3")]
    pub total_supply: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTxHistoryArg {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// Max transactions to return
    #[prost(uint32, tag = "2")]
    pub limit: u32,
    /// Pagination offset
    #[prost(uint32, tag = "3")]
    pub offset: u32,
    /// Cursor-based pagination
    #[prost(bytes = "vec", tag = "4")]
    pub after_txid: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxHistoryEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    /// 0 if unconfirmed
    #[prost(uint64, tag = "2")]
    pub height: u64,
    /// Block timestamp
    #[prost(uint32, tag = "3")]
    pub time: u32,
    /// Net balance change for this address
    #[prost(int64, tag = "4")]
    pub balance_change: i64,
    /// Transaction fee
    #[prost(uint64, tag = "5")]
    pub fee: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTxHistoryReply {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<TxHistoryEntry>,
    #[prost(uint64, tag = "2")]
    pub total_count: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub fee: u64,
    #[prost(uint32, tag = "3")]
    pub size: u32,
    /// Entry time
    #[prost(uint64, tag = "4")]
    pub time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMempoolArg {
    #[prost(uint32, tag = "1")]
    pub limit: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMempoolReply {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MempoolEntry>,
    #[prost(uint64, tag = "2")]
    pub total_count: u64,
    #[prost(uint64, tag = "3")]
    pub total_size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSupplyInfoArg {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSupplyInfoReply {
    /// Total supply in satoshis
    #[prost(int64, tag = "1")]
    pub total_supply: i64,
    /// Circulating supply (excluding locked)
    #[prost(int64, tag = "2")]
    pub circulating_supply: i64,
    /// Height at which this was calculated
    #[prost(uint64, tag = "3")]
    pub block_height: u64,
    /// Block hash at calculation time
    #[prost(string, tag = "4")]
    pub block_hash: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod compact_tx_streamer_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CompactTxStreamerServer.
    #[async_trait]
    pub trait CompactTxStreamer: Send + Sync + 'static {
        /// ========== Server Info ==========
        async fn get_lightd_info(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::LightdInfo>, tonic::Status>;
        /// ========== Block Services ==========
        async fn get_latest_block(
            &self,
            request: tonic::Request<super::ChainSpec>,
        ) -> std::result::Result<tonic::Response<super::BlockId>, tonic::Status>;
        async fn get_block(
            &self,
            request: tonic::Request<super::BlockId>,
        ) -> std::result::Result<tonic::Response<super::CompactBlock>, tonic::Status>;
        /// Server streaming response type for the GetBlockRange method.
        type GetBlockRangeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::CompactBlock, tonic::Status>,
            >
            + Send
            + 'static;
        async fn get_block_range(
            &self,
            request: tonic::Request<super::BlockRange>,
        ) -> std::result::Result<
            tonic::Response<Self::GetBlockRangeStream>,
            tonic::Status,
        >;
        /// ========== Transaction Services ==========
        async fn get_transaction(
            &self,
            request: tonic::Request<super::TxFilter>,
        ) -> std::result::Result<tonic::Response<super::RawTransaction>, tonic::Status>;
        async fn send_transaction(
            &self,
            request: tonic::Request<super::RawTransaction>,
        ) -> std::result::Result<tonic::Response<super::SendResponse>, tonic::Status>;
        /// ========== Address Services ==========
        async fn get_address_utxos(
            &self,
            request: tonic::Request<super::GetAddressUtxosArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetAddressUtxosReply>,
            tonic::Status,
        >;
        /// Server streaming response type for the GetAddressUtxosStream method.
        type GetAddressUtxosStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AddressUtxo, tonic::Status>,
            >
            + Send
            + 'static;
        async fn get_address_utxos_stream(
            &self,
            request: tonic::Request<super::GetAddressUtxosArg>,
        ) -> std::result::Result<
            tonic::Response<Self::GetAddressUtxosStreamStream>,
            tonic::Status,
        >;
        async fn get_balance(
            &self,
            request: tonic::Request<super::GetBalanceArg>,
        ) -> std::result::Result<tonic::Response<super::GetBalanceReply>, tonic::Status>;
        async fn get_address_stats(
            &self,
            request: tonic::Request<super::GetAddressStatsArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetAddressStatsReply>,
            tonic::Status,
        >;
        async fn get_tx_history(
            &self,
            request: tonic::Request<super::GetTxHistoryArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetTxHistoryReply>,
            tonic::Status,
        >;
        /// ========== Wallet Ranking (Junkcoin Extension) ==========
        async fn get_top_wallets(
            &self,
            request: tonic::Request<super::GetTopWalletsArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetTopWalletsReply>,
            tonic::Status,
        >;
        async fn get_wallet_rank(
            &self,
            request: tonic::Request<super::GetWalletRankArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetWalletRankReply>,
            tonic::Status,
        >;
        async fn get_rich_list(
            &self,
            request: tonic::Request<super::GetRichListArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetRichListReply>,
            tonic::Status,
        >;
        /// ========== Network Info ==========
        async fn get_mempool(
            &self,
            request: tonic::Request<super::GetMempoolArg>,
        ) -> std::result::Result<tonic::Response<super::GetMempoolReply>, tonic::Status>;
        async fn get_supply_info(
            &self,
            request: tonic::Request<super::GetSupplyInfoArg>,
        ) -> std::result::Result<
            tonic::Response<super::GetSupplyInfoReply>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CompactTxStreamerServer<T: CompactTxStreamer> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: CompactTxStreamer> CompactTxStreamerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CompactTxStreamerServer<T>
    where
        T: CompactTxStreamer,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/junkcoin.lightwallet.CompactTxStreamer/GetLightdInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetLightdInfoSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<T: CompactTxStreamer> tonic::server::UnaryService<super::Empty>
                    for GetLightdInfoSvc<T> {
                        type Response = super::LightdInfo;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_lightd_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetLightdInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetLatestBlock" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestBlockSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::ChainSpec>
                    for GetLatestBlockSvc<T> {
                        type Response = super::BlockId;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChainSpec>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_latest_block(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetLatestBlockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetBlock" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::BlockId> for GetBlockSvc<T> {
                        type Response = super::CompactBlock;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BlockId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_block(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBlockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetBlockRange" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockRangeSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::ServerStreamingService<super::BlockRange>
                    for GetBlockRangeSvc<T> {
                        type Response = super::CompactBlock;
                        type ResponseStream = T::GetBlockRangeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BlockRange>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_block_range(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBlockRangeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetTransaction" => {
                    #[allow(non_camel_case_types)]
                    struct GetTransactionSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::TxFilter>
                    for GetTransactionSvc<T> {
                        type Response = super::RawTransaction;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TxFilter>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_transaction(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetTransactionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/SendTransaction" => {
                    #[allow(non_camel_case_types)]
                    struct SendTransactionSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::RawTransaction>
                    for SendTransactionSvc<T> {
                        type Response = super::SendResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RawTransaction>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::send_transaction(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SendTransactionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetAddressUtxos" => {
                    #[allow(non_camel_case_types)]
                    struct GetAddressUtxosSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetAddressUtxosArg>
                    for GetAddressUtxosSvc<T> {
                        type Response = super::GetAddressUtxosReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAddressUtxosArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_address_utxos(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetAddressUtxosSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetAddressUtxosStream" => {
                    #[allow(non_camel_case_types)]
                    struct GetAddressUtxosStreamSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::ServerStreamingService<super::GetAddressUtxosArg>
                    for GetAddressUtxosStreamSvc<T> {
                        type Response = super::AddressUtxo;
                        type ResponseStream = T::GetAddressUtxosStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAddressUtxosArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_address_utxos_stream(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetAddressUtxosStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetBalance" => {
                    #[allow(non_camel_case_types)]
                    struct GetBalanceSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetBalanceArg>
                    for GetBalanceSvc<T> {
                        type Response = super::GetBalanceReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBalanceArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_balance(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBalanceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetAddressStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetAddressStatsSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetAddressStatsArg>
                    for GetAddressStatsSvc<T> {
                        type Response = super::GetAddressStatsReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAddressStatsArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_address_stats(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetAddressStatsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetTxHistory" => {
                    #[allow(non_camel_case_types)]
                    struct GetTxHistorySvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetTxHistoryArg>
                    for GetTxHistorySvc<T> {
                        type Response = super::GetTxHistoryReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTxHistoryArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_tx_history(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetTxHistorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetTopWallets" => {
                    #[allow(non_camel_case_types)]
                    struct GetTopWalletsSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetTopWalletsArg>
                    for GetTopWalletsSvc<T> {
                        type Response = super::GetTopWalletsReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTopWalletsArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_top_wallets(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetTopWalletsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetWalletRank" => {
                    #[allow(non_camel_case_types)]
                    struct GetWalletRankSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetWalletRankArg>
                    for GetWalletRankSvc<T> {
                        type Response = super::GetWalletRankReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetWalletRankArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_wallet_rank(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetWalletRankSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetRichList" => {
                    #[allow(non_camel_case_types)]
                    struct GetRichListSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetRichListArg>
                    for GetRichListSvc<T> {
                        type Response = super::GetRichListReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRichListArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_rich_list(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetRichListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetMempool" => {
                    #[allow(non_camel_case_types)]
                    struct GetMempoolSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetMempoolArg>
                    for GetMempoolSvc<T> {
                        type Response = super::GetMempoolReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMempoolArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_mempool(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetMempoolSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/junkcoin.lightwallet.CompactTxStreamer/GetSupplyInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetSupplyInfoSvc<T: CompactTxStreamer>(pub Arc<T>);
                    impl<
                        T: CompactTxStreamer,
                    > tonic::server::UnaryService<super::GetSupplyInfoArg>
                    for GetSupplyInfoSvc<T> {
                        type Response = super::GetSupplyInfoReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSupplyInfoArg>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CompactTxStreamer>::get_supply_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetSupplyInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: CompactTxStreamer> Clone for CompactTxStreamerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: CompactTxStreamer> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: CompactTxStreamer> tonic::server::NamedService
    for CompactTxStreamerServer<T> {
        const NAME: &'static str = "junkcoin.lightwallet.CompactTxStreamer";
    }
}
